version: "3.8"

services:
  studio:
    build:
      context: ..
      dockerfile: studio/Dockerfile
      target: dev
    ports:
      - 8082:8082
  mail:
    container_name: supabase-mail
    image: inbucket/inbucket:3.0.3
    ports:
      - '2500:2500' # SMTP
      - '9000:9000' # web interface
      - '1100:1100' # POP3
  auth:
    environment:
      - GOTRUE_SMTP_USER=
      - GOTRUE_SMTP_PASS=
  meta:
    ports:
      - 5555:8080
  storage:
    volumes:
      - /var/lib/storage
